---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hello-world
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.4
spec:
  releaseName: hello-world
  chart:
    git: git@github.com:davidfragalaureano/gitops-helm-operator
    path: charts/hello-world
    ref: master
  values:
    image: davidfraga610/hello-world:0.1.0
    replicaCount: 2
